### ISSUE TITLE
Finding a new name

### ISSUE THREAD

**Issue by tknobi** [bruno-robot/bruno-robot#12]
We need a new name, because there is already a soccer-playing robot named [Bruno](https://robots.ieee.org/robots/dribbler/).
This is to prevent confusion.

* Deadline: Start of [European Robocup Junior](https://2022.robocupjunior.eu/) (June 1st, 2022), as we want to present the concept to other teams and/or official there.
* We should use the term **KIT** instead of **ROBOT**. This is to clarify that we do not want to provide robot instructions, but only instructions on how to build components.
* The idea to use an acronym was generally accepted in the meeting, but some creativity is still missing :smile: 

Anyone with an idea, post a comment in this issue. Everyone can give comments a :+1: , the comment with the most :+1: on May 30, 2022 20:00 (German time) wins.

**Comment by tknobi** [comment]
**CoRSN** kit:  **Co**mponents for **R**obocupJunior **S**occer **N**ewcomers

**Comment by stiebel** [comment]
RoSoNeSt kit
Robocup Soccer New Standard

**Comment by stiebel** [comment]
RoSoNeCo kit
Robocup Soccer Newcomer Components

**Comment by tknobi** [comment]
**CoRoSoN** kit:  **Co**mponents for **Ro**bocupJunior **So**ccer **N**ewcomers

**Comment by stiebel** [comment]
CoRoSoN sounds great to me!
It actually remembers me of Coruscant, the center of power in Star Wars...
That fits !

**Comment by f-gaul** [comment]
Here are two more options:
1.) **Be**ginner **R**obocup **S**occ**er** **K**it -> BeRSerK

**Comment by f-gaul** [comment]
2.) **B**eginner **R**obocup Jun**i**or **S**occer **K**it -> BRiSK

**Comment by f-gaul** [comment]
Keep It Simple -> KIS

**Comment by stiebel** [comment]
Hello altogether,
I have seen plenty of good ideas here.
My favorite is CoRoSoN, but I also like KIS, even if I would make it a
Keep It Simple Soccer -Kit -> KISS-Kit, although thinking about it, this could pop up in wrong queries...

However, we (you) should get a final name an Tuesday, so I can spread the good news to the (European) World 
from Wednesday on.

Greetings,
Roland

**Comment by f-gaul** [comment]
I think
Keep It Simple Soccer -Kit -> KISS-Kit 
is fine too.
